from pydantic import BaseModel
from typing import Optional, List


# ── Request ──────────────────────────────────────────────────────────────────

class SuggestionContext(BaseModel):
    currentSetId: Optional[str] = None   # prioritise cards from this set
    streakAtRisk: Optional[bool] = False  # streak about to break


class SuggestionRequest(BaseModel):
    userId: str
    sessionDuration: int = 20   # minutes
    topN: int = 10
    context: Optional[SuggestionContext] = None


# ── Response ─────────────────────────────────────────────────────────────────

class SuggestedWord(BaseModel):
    cardId: str
    setId: str
    word: str
    meaning: str
    phonetic: Optional[str] = None
    priority_score: float
    reason: str                 # generated by Gemini
    tag: str                    # overdue | due_today | new_word | difficult
    due_days_ago: Optional[int] = None   # positive = overdue, None = not overdue


class SessionMeta(BaseModel):
    total_suggested: int
    due_count: int
    new_count: int
    review_count: int
    estimated_duration_min: int


class SuggestionResponse(BaseModel):
    suggested_words: List[SuggestedWord]
    session_meta: SessionMeta
